"use client";

import { motion } from "framer-motion";
import { ArrowRight, TrendingUp } from "lucide-react";
import { Reveal } from "@/components/fx/Reveal";

const before = {
  headline: "Software Developer at Company",
  bio: "I work with technology and like to learn new things.",
  followers: "312",
  engagement: "0.4%",
  recruiterViews: "2 / month"
};

const after = {
  headline: "AI Engineer · Building scalable automation systems",
  bio: "I architect AI-powered products that ship fast and scale globally. Open to high-impact roles and strategic partnerships.",
  followers: "14.2K",
  engagement: "9.4%",
  recruiterViews: "38 / month"
};

export function BeforeAfter() {
  return (
    <section className="py-24 md:py-32 border-t border-white/[0.06]">
      <div className="container">
        <Reveal>
          <p className="text-xs uppercase tracking-[0.3em] text-bone-400 text-center">
            Transformation
          </p>
          <h2 className="h-display mt-3 text-center text-3xl md:text-5xl text-gradient">
            From invisible to unmissable.
          </h2>
          <p className="mt-4 text-center text-bone-300 max-w-xl mx-auto">
            BLACKLINK AI rewrites your profile, generates authority content and
            puts you in front of the right people — automatically.
          </p>
        </Reveal>

        <div className="mt-14 grid grid-cols-1 md:grid-cols-2 gap-4 max-w-4xl mx-auto">
          <Reveal delay={0.05}>
            <ProfileCard label="Before" data={before} dim />
          </Reveal>
          <Reveal delay={0.15}>
            <ProfileCard label="After BLACKLINK AI" data={after} />
          </Reveal>
        </div>
      </div>
    </section>
  );
}

function ProfileCard({
  label,
  data,
  dim = false
}: {
  label: string;
  data: typeof before;
  dim?: boolean;
}) {
  return (
    <motion.div
      whileHover={{ y: -3 }}
      transition={{ type: "spring", stiffness: 260, damping: 22 }}
      className={`card p-6 relative overflow-hidden ${dim ? "opacity-60" : ""}`}
    >
      {!dim && (
        <div className="absolute -top-16 -right-16 h-40 w-40 rounded-full bg-white/[0.06] blur-3xl" />
      )}
      <p className="text-[11px] uppercase tracking-[0.2em] text-bone-400">{label}</p>

      <div className="mt-4 flex items-center gap-3">
        <div className="h-12 w-12 rounded-full bg-gradient-to-br from-white/30 to-white/5 border border-white/10" />
        <div>
          <p className="text-sm font-medium leading-tight">{data.headline}</p>
        </div>
      </div>

      <p className="mt-4 text-xs text-bone-300 leading-relaxed">{data.bio}</p>

      <div className="mt-5 grid grid-cols-3 gap-2">
        <Metric label="Followers" value={data.followers} />
        <Metric label="Engagement" value={data.engagement} />
        <Metric label="Recruiters" value={data.recruiterViews} />
      </div>

      {!dim && (
        <div className="mt-4 flex items-center gap-1.5 text-xs text-bone-200">
          <TrendingUp className="h-3.5 w-3.5" />
          Generated by BLACKLINK AI
          <ArrowRight className="h-3 w-3 ml-auto" />
        </div>
      )}
    </motion.div>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-2.5 text-center">
      <p className="text-[10px] uppercase tracking-[0.15em] text-bone-400">{label}</p>
      <p className="mt-1 text-sm font-semibold">{value}</p>
    </div>
  );
}
